extends:
  - '@dynamicyield'
rules:
  # disabled during migration to the new eslint config
  '@typescript-eslint/no-unused-vars': 0
  no-unused-vars: 0
  jsx-a11y/anchor-has-content: off
  react/jsx-no-target-blank: off
  comma-dangle:
    - error
    - arrays: never
      exports: never
      functions: never
      imports: never
      objects: never
